### ISSUE TITLE
 Neuromatch 4.0 Conference blog

### ISSUE THREAD

**Issue by Agrover112** [OREL-group/Neuromatch#9]
Writing a blog on OREL medium page about some interesting flask talks I found in Neuromatch 4.0 Conference

**Comment by jesparent** [comment]
@Agrover112  do you have a shared document / google doc that you are working on this?

**Comment by Agrover112** [comment]
> @Agrover112  do you have a shared document / google doc that you are working on this? 

It's on Medium :)

**Comment by jesparent** [comment]
well done @Agrover112
